name: build coolsnowwolf/lede X86_64
on: 
  push:
  schedule:
  - cron: 0 0 * * 2
  watch:
    types: started
  
#env:
#  REPO_URL: https://github.com/coolsnowwolf/lede
#  REPO_BRANCH: master
#  CONFIG_FILE: .config
#  SSH_ACTIONS: false
#  UPLOAD_BIN_DIR: false
#  UPLOAD_FIRMWARE: true
#  UPLOAD_COWTRANSFER: false
#  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04  #latest #ubuntu-18.04 #20.04 
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: 系统环境更新、清理空间 | Installation depends
      run: |
        docker rmi `docker images -q`
        #sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo dpkg --configure -a
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 钉钉通知
      uses: ghostoy/dingtalk-action@master
      with:
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=36a1e8b0ef6ba7ccddd320cfb9fceae841917ed4850a329aedc52f87d05a5877"
        msgtype: markdown
        content: |
          {
            "title": "github.workflow 通知：",
            "text": "**lede-X86_64.yml <font color=#00FF00 size=4>环境准备完成</font>::准备下载源码编译。"
          }
        secret: "SECb72bffd2104d07454dc9754a6bf0a9f4fd1e8bf110de7b87d1f5af7a14e0598a"
  
    - name: 下载openwrt coolsnowwolf lean源代码 | Clone source code
      run: | 
        git clone https://github.com/coolsnowwolf/lede
        cd lede
        #echo "src-git OpenClash https://github.com/vernesong/OpenClash.git" >> feeds.conf.default
        #git clone https://github.com/vernesong/OpenClash.git ./package/OpenClash
        # Clone openclash 项目
        mkdir package/luci-app-openclash
        cd package/luci-app-openclash
        git init
        #git remote add -f origin https://github.com/vernesong/OpenClash.git
        curl -fsSL https://github.com/chenxinxing/gfw/raw/master/openwrt/openclash.git.config > .git/config
        git config core.sparsecheckout true
        echo "luci-app-openclash" >> .git/info/sparse-checkout
        git pull --depth 1 origin master
        git branch --set-upstream-to=origin/master master
        # 编译 po2lmo (如果有po2lmo可跳过)
        pushd luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd
        cd ../..
        #sed -i 's/\.disabled=1/\.disabled=0/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
        #sed -i 's/\.ssid=OpenWrt/\.ssid=stoneson/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
        sed -i "s/set system\.\@system\[-1\]\.timezone='UTC'/set system.@system[-1].timezone='CST-8'/" ./package/base-files/files/bin/config_generate
        sed -i "s/0\.openwrt\.pool\.ntp\.org/ntp1.aliyun.com/" ./package/base-files/files/bin/config_generate
        sed -i "s/1\.openwrt\.pool\.ntp\.org/time1.cloud.tencent.com/" ./package/base-files/files/bin/config_generate
        echo "net.netfilter.nf_conntrack_max=65535" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
        echo "net.ipv4.ip_forward = 1" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
        make clean && make dirclean
        rm -rf ./tmp && rm -rf .config
        curl -fsSL https://github.com/chenxinxing/gfw/raw/master/config.lede.X64 > .config
        ./scripts/feeds update -a && ./scripts/feeds install -a
        make defconfig && make prereq
        make download -j8
        make V=s -j$(nproc)
        #make package/luci-app-openclash/luci-app-openclash/compile V=99

    - name: 钉钉通知
      uses: ghostoy/dingtalk-action@master
      with:
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=36a1e8b0ef6ba7ccddd320cfb9fceae841917ed4850a329aedc52f87d05a5877"
        msgtype: markdown
        content: |
          {
            "title": "github.workflow 构建完成通知：",
            "text": "**lede-X86_64.yml <font color=#FF0000 size=4>构建完成</font>"
          }
        secret: "SECb72bffd2104d07454dc9754a6bf0a9f4fd1e8bf110de7b87d1f5af7a14e0598a"

    - name : 上传编译包｜Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: lede-X86_64
        path: lede/bin
        
    - name: 钉钉通知
      uses: ghostoy/dingtalk-action@master
      with:
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=36a1e8b0ef6ba7ccddd320cfb9fceae841917ed4850a329aedc52f87d05a5877"
        msgtype: markdown
        content: |
          {
            "title": "github.workflow 编译完成通知：",
            "text": "**lede-X86_64.yml <font color=#000000 size=4>上传编译包｜Upload artifact完成</font>"
          }
        secret: "SECb72bffd2104d07454dc9754a6bf0a9f4fd1e8bf110de7b87d1f5af7a14e0598a"

