name: build OpenWrt
on: 
  #push:
  #schedule:
  #- cron: 0 0 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest  #ubuntu-latest #ubuntu-18.04 #20.04 
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: 系统环境更新、清理空间 | Installation depends
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        #sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo dpkg --configure -a
        sudo apt-get -u update
        #sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs  git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo df -h
        pwd

    - name: 下载openwrt 和 coolsnowwolf lean源代码
      run: |   #下载原版内容openwrt
        git clone https://github.com/openwrt/openwrt
        git clone https://github.com/coolsnowwolf/lede
        #git clone https://github.com/chinaboy2345/luci-app-ramfree.git openwrt/package/chenxx/luci-app-ramfree
        #git clone https://github.com/zxl78585/luci-app-filetransfer.git openwrt/package/chenxx/luci-app-filetransfer
        #git clone https://github.com/deplives/luci-app-turboacc.git openwrt/package/chenxx/luci-app-turboacc
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git openwrt/package/chenxx/openwrt-vlmcsd
        git clone https://github.com/flytosky-f/luci-app-vlmcsd.git openwrt/package/chenxx/luci-app-vlmcsd
        #git clone https://github.com/mitsukileung/luci-app-aliyundrive-webdav.git openwrt/package/chenxx/luci-app-aliyundrive-webdav
        #mkdir -p openwrt/package/chenxx/parted && \
        #wget https://raw.githubusercontent.com/lisaac/luci-app-diskman/master/Parted.Makefile -O openwrt/package/chenxx/parted/Makefile
        #cp -r lede/package/lean/pdnsd-alt openwrt/package/chenxx/
        #cp -r lede/package/lean/*vsftpd* openwrt/package/chenxx/
        #cp -r lede/package/lean/*aliyundrive-webdav* openwrt/package/chenxx/
        rm -rf lede/


    - name: 修改配置信息 ｜Generate config file
      run: |
       cd openwrt
       #echo "src-git OpenClash https://github.com/vernesong/OpenClash.git" >> feeds.conf.default
       sed -i 's/root::0:0:99999:7:::/root:\$1\$wEehtjxj\$YBu4quNfVUjzfv8p\/PBo5\.:0:0:99999:7:::/' ./package/base-files/files/etc/shadow
       #sed -i 's/\.disabled=1/\.disabled=0/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
       #sed -i 's/\.ssid=OpenWrt/\.ssid=stoneson/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
       #sed -i "s/set system\.\@system\[-1\]\.hostname='OpenWrt'/set system.@system[-1].hostname='WNDR4300'/" ./package/base-files/files/bin/config_generate
       sed -i "s/set system\.\@system\[-1\]\.timezone='UTC'/set system.@system[-1].timezone='CST-8'/" ./package/base-files/files/bin/config_generate
       sed -i "s/0\.openwrt\.pool\.ntp\.org/ntp1.aliyun.com/" ./package/base-files/files/bin/config_generate
       sed -i "s/1\.openwrt\.pool\.ntp\.org/time1.cloud.tencent.com/" ./package/base-files/files/bin/config_generate
       echo "net.netfilter.nf_conntrack_max=65535" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
       echo "net.ipv4.ip_forward = 1" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
       #sed -i 's/+libpcre/+libpcre2/g' ./package/feeds/telephony/freeswitch/Makefile
       rm -fr bin/ dl/ staging_dir/ build_dir/ tmp/

    - name: Clone openclash 项目
      run: |
       cd openwrt
       mkdir -p package/chenxx/luci-app-openclash
       cd package/chenxx/luci-app-openclash
       git init
       git remote add -f origin https://github.com/vernesong/OpenClash.git
       git config core.sparsecheckout true
       echo "luci-app-openclash" >> .git/info/sparse-checkout
       git pull --depth 1 origin master
       git branch --set-upstream-to=origin/master master

       # 编译 po2lmo (如果有po2lmo可跳过)
       pushd luci-app-openclash/tools/po2lmo
       make && sudo make install
       popd

    - name: 开始项目编译
      run: |
       cd openwrt
       ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a
       curl -fsSL https://github.com/chenxinxing/gfw/raw/master/openwrt/config.buildinfo  > .config
       ./scripts/feeds update -a && ./scripts/feeds install -a
       make defconfig && make prereq
       make download -j8
       make -j1

    - name: 钉钉通知
      uses: ghostoy/dingtalk-action@master
      with:
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=36a1e8b0ef6ba7ccddd320cfb9fceae841917ed4850a329aedc52f87d05a5877"
        msgtype: markdown
        content: |
          {
            "title": "github.workflow 通知：",
            "text": "**WNDR4300V1.yml <font color=#FFFF00 size=4>构建完成</font>::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          }
        secret: "SECb72bffd2104d07454dc9754a6bf0a9f4fd1e8bf110de7b87d1f5af7a14e0598a"

    - name : 上传编译包｜Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: openwrt
        path: openwrt/bin
